version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27030:27017"
    networks:
      - nestjs-network
    volumes:
      - db:/data/db
  api:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - nestjs-network
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
volumes:
  mongodb:
networks:
  nestjs-network:
    driver: bridge


